respect the dhcp interface state when generating the dhcpd.conf
zentyal/zentyal pull request #1905
Opened 2019-11-01 21:37 UTC by patphobos

fix #1903
currently the dhcpd.conf is generated with dhcp disabled interfaces, so the isc-dhcpd-server is answering dhcp request on this interfaces.

2019-11-02 11:19 UTC, Neustradamus commented
@brunolorente: Have you seen this PR and the ticket?

2020-04-15 05:36 UTC, Neustradamus commented
@brunolorente: Any news?

2020-09-10 09:04 UTC, brunolorente commented on main/dhcp/src/EBox/DHCP.pm
> +sub dhcpEnabled
About the method name, in order to follow the project's code style, it may be named "ifaceStatus".
And please, try to not to use ternary operators.

2020-09-10 09:19 UTC, brunolorente requested changes
Hi @patphobos,

Many many thanks for your contribution and your time investment on the project.

Please see my comment and apply the requested "fix" in order to merge your fix.

On the other hand, could you please make this pull request over the develop branch? 

This PR works but please, keep in mind my comments!

2020-09-10 09:43 UTC, patphobos commented
Hi @brunolorente 

requested modifications has been applied on fix-dhcp-disabled-interface-not-disabled and pull request is now against develop branch.

2020-09-22 10:01 UTC, brunolorente approved these changes
Wow, what a fast reply, thank you very much @patphobos!

2020-09-22 10:01 UTC, merged